GROQ_API_KEY = "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"
QWEN_API_KEY = "sk-38048f1aaf7d4a5fa75d7f95c666f455"
DEEPSEEK_API_KEY    = "sk-72109bd044a94d8490417d6af2085945"
GEMINI_API_KEY      = "AIzaSyAefKQdE9zugylA9Pgdn3j-z8jqc2K6zvk"
GROQ_API_KEY        = "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"
OPENROUTER_API_KEY  = "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"
HF_API_KEY          = "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"
SUPABASE_URL        = "https://zhphydiwydiawoyixujb.supabase.co/rest/v1/"
SUPABASE_KEY        = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpocGh5ZGl3eWRpYXdveWl4dWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwNDUyMDcsImV4cCI6MjA5NDYyMTIwN30.BZxutW7G6QZvJcj6q-3UpCtT_yy4WRVsNoIgnuJ6MiE"
